apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      runAsUser: 1000                      # Run the container as a specific user ID
      capabilities:
        add: ["NET_ADMIN"]                 # Add specific Linux capabilities
      readOnlyRootFilesystem: true         # Mount the container's root filesystem as read-only
    volumeMounts:
    - name: cache-volume
      mountPath: /var/cache/nginx
    - name: runtime-volume
      mountPath: /var/run
  volumes:
    - name: cache-volume
      emptyDir: {}
    - name: runtime-volume
      emptyDir: {}
